### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JessicaSarah** [vinhloc1996/Decrypt-PluralSight-Videos#2]
Cannot find the database path.
Error occured: Object reference not set to an instance of an object.
   at DecryptPluralSightVideos.Decryptor.GetCourseFromDb(String folderCoursePath
) in **E:\Work\DecryptPluralSightVideos\DecryptPluralSightVideos\Decryptor.cs:line**
 507
   at DecryptPluralSightVideos.Decryptor.DecryptAllFolders(String folderPath, St
ring outputFolder) in E:\Work\DecryptPluralSightVideos\DecryptPluralSightVideos\
Decryptor.cs:line 118
   at DecryptPluralSightVideos.Program.Main(String[] args) in E:\Work\DecryptPlu
ralSightVideos\DecryptPluralSightVideos\Program.cs:line 36

**Comment by vinhloc1996** [comment]
Sorry for a very late response because I didn't get notified of the issue. I think you provide the wrong path of the database. Please note that the database was generated and stored in `C:\Users\<YourUserName>\AppData\Local\Pluralsight\pluralsight.db`.
Sorry again for the delay response.

**Comment by smithy49** [comment]
There seems to be a bug.
I have no F: drive but the program seems to be searching there.
I'm running the program as:
DecryptPluralSightVideos /F "C:\Users ...

Cannot find the database path.
Error occured: Object reference not set to an instance of an object.
   at DecryptPluralSightVideos.Decryptor.GetCourseFromDb(String folderCoursePath) in F:\Decrypt-PluralSight-Videos\DecryptPluralSightVideos\Decryptor.cs:line 512
   at DecryptPluralSightVideos.Decryptor.DecryptAllFolders(String folderPath, String outputFolder) in F:\Decrypt-PluralSight-Videos\DecryptPluralSightVideos\Decryptor.cs:line 115
   at DecryptPluralSightVideos.Program.Main(String[] args) in F:\Decrypt-PluralSight-Videos\DecryptPluralSightVideos\Program.cs:line 36

**Comment by vinhloc1996** [comment]
Hi @smithy49, please provide the full command you have entered. Maybe you didn't provide the database path, the `F:\` drive is the drive that I have used to compile the source code, it's not the drive in your computer. Please re-open this issue or create the new one to the easier follow.

**Comment by itolimaesther** [comment]
Please how can i resolve this issue.am having this issue too
