### ISSUE TITLE
path is not on the disk error

### ISSUE THREAD

**Issue by Relwe** [vinhloc1996/Decrypt-PluralSight-Videos#4]
every time i'm running the decryptor i'm getting this error:
```
Error occured: Attempted to access a path that is not on the disk.
   at DecryptPluralSightVideos.Decryptor.DecryptAllFolders(String folderPath, String outputFolder) in E:\Work\DecryptPluralSightVideos\DecryptPluralSightVideos\Decryptor.cs:line 100
   at DecryptPluralSightVideos.Program.Main(String[] args) in E:\Work\DecryptPluralSightVideos\DecryptPluralSightVideos\Program.cs:line 36
```
although all the paths are right and exist.

**Comment by vinhloc1996** [comment]
Hi @Relwe, can I get more specific information on this issue? Like the entire commands you've entered, the course path, output path (if possible).

**Comment by vinhloc1996** [comment]
Hi @Relwe, I think I find your issue, your source path is not correct. You should find the correct source path in here "C:\Users\{YOUR_USER}\AppData\Local\Pluralsight\courses". Replace {YOUR_USER} to your user on your computer to get the correct path.

**Comment by Relwe** [comment]
This is the command I ran
`C:\Users\ariel\Documents\pluralPlayer\DecryptPluralSightVideos_v1.0>DecryptPluralSightVideos.exe /f "C:\Users\ariel\AppData\Local\Pluralsight\courses\" /db "C:\Users\ariel\AppData\Local\Pluralsight\pluralsight.db" /trans /out "c:\temp\"`

**Comment by vinhloc1996** [comment]
Hi @Relwe , You just need to remove the backslash at the end of the source path and output path. The final command should look like this:
`DecryptPluralSightVideos.exe /f "C:\Users\ariel\AppData\Local\Pluralsight\courses" /db "C:\Users\ariel\AppData\Local\Pluralsight\pluralsight.db" /trans /out "c:\temp"`
It should work fine.

**Comment by Relwe** [comment]
Now it is working, thanks.

**Comment by SangamSwadiK** [comment]
Hi @vinhloc1996  I'm facing a similar issue.
`Error occured: Attempted to access a path that is not on the disk.
   at DecryptPluralSightVideos.Decryptor.DecryptAllFolders(String folderPath, String outputFolder) in E:\Work\DecryptPluralSightVideos\DecryptPluralSightVideos\Decryptor.cs:line 100
   at DecryptPluralSightVideos.Program.Main(String[] args) in E:\Work\DecryptPluralSightVideos\DecryptPluralSightVideos\Program.cs:line 36`

I typed in the below:
`C:\Users\Sangam\AppData\Local\Pluralsight\DecryptPluralSightVideos>DecryptPluralSightVideos.exe /F "C:\Users\Sangam\AppData\Local\Pluralsight\courses\" /DB "C:\Users\Sangam\AppData\Local\Pluralsight\pluralsight.db" /TRANS /RM /OUT "F:\Course"`

Please Help.
Thanks in advance.

**Comment by suraj-raghupathi** [comment]
HI 
Even I am facing the same problem.
this is the command which I gave:
 _DecryptPluralSightVideos.exe /f "C:\Users\css116744\AppData\Local\Pluralsight\courses" /db "C:\Users\css116744\AppData\Local\Pluralsight\pluralsight.db" /trans /out "c:\temp"_
 and this is the output I got 
_Start to decrypt all courses...
The Database Connection has been open completely.

Error occured: Attempted to access a path that is not on the disk.
   at DecryptPluralSightVideos.Decryptor.DecryptAllFolders(String folderPath, String outputFolder) in E:\Work\DecryptPluralSightVideos\DecryptPluralSightVideos\Decryptor.cs:line 111
   at DecryptPluralSightVideos.Program.Main(String[] args) in E:\Work\DecryptPluralSightVideos\DecryptPluralSightVideos\Program.cs:line 36_

**Comment by vinhloc1996** [comment]
Hi @suraj-raghupathi, could you check the path "c:\temp" is valid? If the `C:\` drive doesn't contain any folder name `temp`, you can create one and try again. If that doesn't solve your problem, can you re-check the path of the database? Let me know if it works or not.
